### PR TITLE
Making status endpoint to accept array

### PR DESCRIPTION
**Pull request by opishcheiko**
Changing the exiting endpoint to accept a string.
My idea is to use it this way:
/api/v1/tests_history/test_status/**1+3+5**/test_run/123
so now accepting the string, extracting numbers from that string and putting it into an array. Then in the query just filtering IN that array of values.

@Jnegrier I am ready for your suggestions 🙈

### CODE REVIEW

**Comment by opishcheiko** [comment]
@cristianmoisa sorry, that didn't call you for that one, wanted to start googling myself, so we don't spend too much time with you and it worked quite easily (I think it, but Juan might destroy my idea hahaha). We can catch up on the frontend part or on something else 🙏

**Comment by Jnegrier** [comment]
Hey @opishcheiko your approach is actually really interesting, I actually like it because it keeps the consistency of the endpoint definition. But.... normally the way to send an array using a GET method, is to use the same name for each value you want to send... mmmm its better to show an example:

For an endpoint like this, the key is `request.args.getlist`, which will gather all the values from the param

```
@app.route("/test_array_params", methods=["GET"])
def check_array_param():
    logger.info("#### Checking array received: ")
    logger.info(request.args.getlist('test_status'))
    resp = jsonify({"test_status": request.args.getlist('test_status')})
    resp.status_code = 200

    return resp
```

To make a request to test endpoint, try with http://localhost:5000/test_array_params?test_status=1&test_status=2&&test_status=3

It should return a list with ['1', '2', '3']

**Comment by Jnegrier** [comment]
If we follow the example I posted, we would end requesting information like http://localhost:5000/test_array_params?test_status=1&test_status=2&test_status=3&test_run_id=33 (just adding test_run_id)

In your way, it would be http://localhost:5000/api/v1/tests_history/test_status/1+3+5/test_run/123 which looks more friendly I think

**Comment by opishcheiko** [comment]
> It's not the common approach to send this type of data, but looks good 👍

Hahaha, thanks for explaining Juan, I can change it to be the proper way no problem, I won't be upset, really! I invented this way, I am happy to follow the code standards

**Pull request merged**
